* 키보드 이벤트 처리

In [1]:
import numpy as np
import cv2

In [5]:
width, height = 512, 512
x, y = width//2, height//2
R = 50

direction = 0  # 0 :right, 1: down, 2:left, 3: up

while True:
    key = cv2.waitKeyEx(30)
    if key == 0x1B:
        break
    
    # 방향키처리
    elif key == 0x270000: # right
        direction = 0
    elif key == 0x280000: # down
        direction = 1
    elif key == 0x250000: # left
        direction = 2
    elif key == 0x260000: # up
        direction = 3        
     
    # 방향에 맞게 x, y 좌표 설정
    if direction == 0:
        x += 10
    elif direction == 1:
        y += 10
    elif direction == 2:
        x -= 10
    else: # 3
        y -= 10
        
    # 경계확인
    if x < R:
        x = R
        direction = 0
    if x > width - R:
        x = width - R
        direction = 2
    
    if y < R:
        y = R
        direction = 1
    if y > height - R:
        y = height - R
        direction = 3
        
    # 지우기, 그리기
    
    img = np.zeros((width, height, 3), np.uint8) + 255
    cv2.circle(img, (x, y), R, (0, 0, 255), -1)
    cv2.imshow('img', img)
    
cv2.destroyAllWindows()

* 마우스 이벤트 처리

In [11]:
img = np.zeros((512, 512, 3), np.uint8) + 255

def onMouse(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        if flags & cv2.EVENT_FLAG_SHIFTKEY:
            cv2.rectangle(param[0], (x-5, y-5), (x+5, y+5), (255, 0, 0))
        else:
            cv2.circle(param[0], (x, y), 5, (255, 0, 0), 3)
    
    elif event == cv2.EVENT_RBUTTONDOWN:
        cv2.circle(param[0], (x, y), 5, (0, 0, 255), 3)
    
    elif event == cv2.EVENT_LBUTTONDBLCLK:
        param[0] = np.zeros((512, 512, 3), np.uint8) + 255
        
        
    cv2.imshow('img', param[0])

############################################
cv2.imshow('img', img)

cv2.setMouseCallback('img', onMouse, [img])
cv2.waitKey()
cv2.destroyAllWindows()

* 트랙바 이벤트 처리

In [13]:
img.shape

(512, 512, 3)

In [21]:
def onChange(pos):
    global img
    r = cv2.getTrackbarPos('R', 'img')
    g = cv2.getTrackbarPos('G', 'img')
    b = cv2.getTrackbarPos('B', 'img')
    img[:] = (b, g, r)
    cv2.imshow('img', img)


img = np.zeros((512, 512, 3), np.uint8) + 255
cv2.imshow('img',img)
cv2.createTrackbar('R', 'img', 0, 255, onChange)
cv2.createTrackbar('G', 'img', 0, 255, onChange)
cv2.createTrackbar('B', 'img', 0, 255, onChange)

cv2.setTrackbarPos('B', 'img', 255)

cv2.waitKey()
cv2.destroyAllWindows()

In [22]:
a1 = np.array([1, 2, 3])
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])

In [24]:
a1[0:2]

array([1, 2])

In [25]:
a2[:1, 1:]

array([[2, 3]])

In [26]:
a2[1:,1:]

array([[5, 6]])

## OpenCV 기본연산

* 형상(shape), 자료형(dtype) 확인

In [30]:
img = cv2.imread('./data/lena.jpg') #cv2.IMREAD_COLOR

In [31]:
type(img)

numpy.ndarray

In [32]:
img.ndim

3

In [33]:
img.shape

(512, 512, 3)

In [34]:
img.dtype

dtype('uint8')

In [35]:
img = img.astype(np.int32)

In [36]:
img.dtype

dtype('int32')

In [37]:
img = np.uint8(img)

In [38]:
img.dtype

dtype('uint8')

* 모양 변경하기

In [39]:
img = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)

In [40]:
img.shape

(512, 512)

In [41]:
512 * 512

262144

In [42]:
img = img.flatten()

In [43]:
img.shape

(262144,)

In [44]:
img = img.reshape(512, 512)

In [45]:
img.shape

(512, 512)

In [46]:
img = img.flatten()

In [47]:
img = img.reshape(-1, 512, 512)

In [48]:
img.shape

(1, 512, 512)

In [51]:
cv2.imshow("img2", img[0])
cv2.waitKey()
cv2.destroyAllWindows()

* 화소 접근 1 : 그레이 스케일영상

In [52]:
img = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)

img[100, 200] = 0

img[100:400, 200:300] = 0

cv2.imshow("img2", img)
cv2.waitKey()
cv2.destroyAllWindows()

array([[163, 162, 161, ..., 170, 154, 130],
       [162, 162, 162, ..., 173, 155, 126],
       [162, 162, 163, ..., 170, 155, 128],
       ...,
       [ 43,  42,  51, ..., 103, 101,  99],
       [ 41,  42,  55, ..., 103, 105, 106],
       [ 42,  44,  57, ..., 102, 106, 109]], dtype=uint8)

* 화소 접근 2 : 컬러 영상

In [59]:
img = cv2.imread('./data/lena.jpg', cv2.IMREAD_COLOR)

img[100, 200] = [255, 0, 0]

img[100:400, 200:300] = [255, 0, 0]

cv2.imshow("img2", img)
cv2.waitKey()
cv2.destroyAllWindows()

* 화소 접근 3 : 채널 접근

In [63]:
img = cv2.imread('./data/lena.jpg', cv2.IMREAD_COLOR)


img[100:400, 200:300, 0] = 255  # Blue channel
img[100:400, 200:300, 1] = 255
img[100:400, 200:300, 2] = 255

cv2.imshow("img2", img)
cv2.waitKey()
cv2.destroyAllWindows()

* 마우스로 ROI 영역 지정 : selecROI()

In [5]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
roi = cv2.selectROI(src)

img = src[roi[1]:roi[1]+roi[3], roi[0]:roi[0]+roi[2]]

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [65]:
roi

(97, 92, 195, 164)

* 마우스로 다중 ROI 영역 지정 : selecROIs()

In [8]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
rois = cv2.selectROIs('src', src, True, False)

for r in rois:
    cv2.rectangle(src, (r[0], r[1]), (r[0]+r[2], r[1]+r[3]), 255)
    
cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()    

In [7]:
rois

array([[  0,   0, 116, 126],
       [127,  79, 140, 194],
       [274, 199, 128, 166]], dtype=int32)

In [9]:
rois

array([[ 70,  87, 120, 118],
       [282, 188, 133, 116]], dtype=int32)

* 블록 평균 영상

In [24]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
dst = np.zeros(src.shape, dtype=src.dtype)

N = 4
height, width = src.shape

h = height // N
w = width // N

for i in range(N):
    for j in range(N):
        x = j*w
        y = i*h
        roi = src[y:y+h, x:x+w]
        dst[y:y+h, x:x+w] = roi.mean()

cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [32]:
src = cv2.imread('./data/lena.jpg')
dst = np.zeros(src.shape, dtype=src.dtype)

N = 64
height, width, _ = src.shape

h = height // N
w = width // N

for i in range(N):
    for j in range(N):
        x = j*w
        y = i*h
        roi = src[y:y+h, x:x+w]
        dst[y:y+h, x:x+w, 0] = roi[:, :, 0].mean()
        dst[y:y+h, x:x+w, 1] = roi[:, :, 1].mean()
        dst[y:y+h, x:x+w, 2] = roi[:, :, 2].mean()

cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

* 영상 복사

In [34]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)

#dst = src        # 참조
dst = src.copy() # 복사

dst[100:400, 200:300] = 0

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()


In [38]:
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)

shape = src.shape[0], src.shape[1], 3
dst = np.zeros(shape, dtype=np.uint8)

#dst[:, :, 0] = src
#dst[:, :, 1] = src
dst[:, :, 2] = src

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

* 채널 분리

In [39]:
src = cv2.imread('./data/lena.jpg')

dst = cv2.split(src)

cv2.imshow('src', src)
cv2.imshow('blue', dst[0])
cv2.imshow('green', dst[1])
cv2.imshow('red', dst[2])
           
cv2.waitKey()
cv2.destroyAllWindows()

In [63]:
src = cv2.imread('./data/candies.png')

b, g, r = cv2.split(src)

cv2.imshow('src', src)
cv2.imshow('blue', b)
cv2.imshow('green', g)
cv2.imshow('red', r)
           
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
* 채널 병합

In [64]:
merge = cv2.merge([b, g, r])

cv2.imshow('merge', merge)           
cv2.waitKey()
cv2.destroyAllWindows()

* 색 변환

In [70]:
src = cv2.imread('./data/lena.jpg')

In [71]:
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
yCrCv = cv2.cvtColor(src, cv2.COLOR_BGR2YCrCb)
hsv = cv2.cvtColor(src, cv2.COLOR_BGR2HSV)


In [67]:
cv2.imshow("gray", gray)
cv2.imshow("yCrCv", yCrCv)
cv2.imshow("hsv", hsv)

cv2.waitKey()
cv2.destroyAllWindows()

In [72]:
bgr = cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)
cv2.imshow("bgr", bgr)
cv2.waitKey()
cv2.destroyAllWindows()

In [73]:
bgr.shape

(512, 512, 3)

In [76]:
512 * 512

262144

In [78]:
(bgr[:, :, 2] == gray).sum()

262144

* 영상 크기 변환

In [80]:
src = cv2.imread("./data/lena.jpg", cv2.IMREAD_GRAYSCALE)

In [85]:
dst1 = cv2.resize(src, dsize=(320, 240))
dst2 = cv2.resize(src, dsize=(0,0), fx=1.5, fy=1.2)

cv2.imshow('dst1', dst1)
cv2.imshow('dst2', dst2)
cv2.waitKey()
cv2.destroyAllWindows()

* 영상 회전 변환

In [86]:
src = cv2.imread("./data/lena.jpg")

dst1 = cv2.rotate(src, cv2.ROTATE_90_CLOCKWISE)
dst2 = cv2.rotate(src, cv2.ROTATE_90_COUNTERCLOCKWISE)

cv2.imshow('dst1', dst1)
cv2.imshow('dst2', dst2)
cv2.waitKey()
cv2.destroyAllWindows()

* 영상 회전 변환 (축소/확대)

In [89]:
src = cv2.imread("./data/lena.jpg")

height, width, channels = src.shape

M1 = cv2.getRotationMatrix2D((height/2, width/2), 45, 0.5)
M2 = cv2.getRotationMatrix2D((height/2, width/2), -45, 0.5)

dst1 = cv2.warpAffine(src, M1, (width, height))
dst2 = cv2.warpAffine(src, M2, (width, height))

cv2.imshow('dst1', dst1)
cv2.imshow('dst2', dst2)
cv2.waitKey()
cv2.destroyAllWindows()

* 영상 어파인 변환 (모서리 3점)

In [90]:
src = cv2.imread("./data/tekapo.bmp")
height, width, channels = src.shape

srcPts = np.float32([[0, 0], [width-1, 0], [width-1, height-1]])
dstPts = np.float32([[50, 50], [width-100, 100], [width-50, height-50]])

M = cv2.getAffineTransform(srcPts, dstPts)

dst = cv2.warpAffine(src, M, (width, height))

cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

* 영상 이동 변환

In [95]:
src = cv2.imread("./data/tekapo.bmp")
height, width, channels = src.shape

M = np.array([[1, 0, 150],
              [0, 1, 100]], dtype=np.float64)

dst = cv2.warpAffine(src, M, (width, height))

cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

* 영상 대칭 변환

In [104]:
src = cv2.imread("./data/eastsea.bmp")
cv2.imshow("src", src)


dst = cv2.flip(src, -1) # 1 : 좌우대칭,  0: 상하대칭,  -1: 좌우, 상하대칭

cv2.imshow("dst", dst)
cv2.waitKey()
cv2.destroyAllWindows()

* 영상 투시 변환

In [120]:
cnt = 0

w = 200
h = 300

srcQuad = np.zeros((4,2), dtype=np.float32)
#dstQuad = np.zeros((4,2), dtype=np.float32)
dstQuad = np.array([[0, 0], [w-1, 0], [w-1, h-1], [0, h-1]], dtype=np.float32)

def onMouse(event, x, y, flags, param):
    global cnt
    
    if event == cv2.EVENT_LBUTTONDOWN:
        if (cnt < 4):
            srcQuad[cnt] = np.array([x, y], dtype=np.float32)
            cv2.circle(param[0], (x, y), 5, (255, 0, 0), 2)
            cv2.imshow('src', param[0])
            cnt += 1
        if (cnt == 4):
            M = cv2.getPerspectiveTransform(srcQuad, dstQuad)
            dst = cv2.warpPerspective(param[0], M, (w, h))
            cv2.imshow('dst', dst)
            

src = cv2.imread("./data/card.bmp")
cv2.imshow("src", src)
cv2.setMouseCallback('src', onMouse, [src])

cv2.waitKey()
cv2.destroyAllWindows()

In [123]:
src = cv2.imread("./data/card.bmp")

cnt = 0
w = 200
h = 300

srcQuad = np.zeros((4,2), dtype=np.float32)
# dstQuad = np.zeros((4,2), dtype=np.float32)
dstQuad = np.array([[0,0],[w-1, 0],[w-1, h-1],[0, h-1]], dtype=np.float32)

def onMouse(event, x, y, flags, param):
    global cnt # 전역변수로 사용
    
    if event == cv2.EVENT_LBUTTONDOWN:
        if (cnt < 4):
            srcQuad[cnt] = np.array([x, y], dtype=np.float32)
            cv2.circle(param[0], (x, y), 5, (255, 0, 0), 2)
            cv2.imshow('src', param[0])
            cnt += 1
        if (cnt ==4):
            M = cv2.getPerspectiveTransform(srcQuad, dstQuad)
            dst = cv2.warpPerspective(param[0], M, (w, h))
            cv2.imshow('dst', dst)


src = cv2.imread("./data/card.bmp")
cv2.imshow('src', src)
cv2.setMouseCallback('src', onMouse, [src])


cv2.waitKey()
cv2.destroyAllWindows()
